### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by pdf** [zhuyie/bidirpc#1]
I've made a number of breaking changes to support my use-cases, primarily extracting the registration functionality to a separate struct so that services can be registered before bringing up the connection, to ensure that they're available on start; and allowing callers to block on the event loop, for HTTP handlers, etc.

Let me know if you're interested in taking them on, otherwise I will fork this properly and create a new package.  You can find the changes here:

https://github.com/pdf/bidirpc/tree/ng

**Comment by zhuyie** [comment]
I think these changes are good. Please send a pull request. Thanks.
